In [83]:
import numpy as np
np.version.full_version

'1.26.4'

In [84]:
my_array = np.array([[1,2,3], [4,5,6]])
np1 = np.array([[1,2],[3,4]])
np2 = np.array([[5,6],[7,8]])
print(np1 + np2) # Matrix sum
print(np1 @ np2) # Matrix product of the inputs
print(np1 * np2) # Matrix Multiplication
print(np2 - np1) # Matrix Substraction
print(np2 + 3)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[4 4]
 [4 4]]
[[ 8  9]
 [10 11]]


In [85]:
np3 = np.array([24, 64, 42])
print(np.divide(np3, 10))
print(np.floor_divide(np3, 10))
print(np.emath.sqrt(9))

[2.4 6.4 4.2]
[2 6 4]
3.0


In [86]:
normal_distribution = np.random.standard_normal((3, 2))
uniform_distribution = np.random.uniform(1, 12, (3, 2))
f_random = np.random.rand(3, 4)
i_random = np.random.randint(2, 42, (3, 4))
zeros = np.zeros((3, 5))
ones = np.ones((3, 5))
print(np.logical_and(i_random>20, i_random<40))

[[False False  True False]
 [False  True False  True]
 [False False  True  True]]


In [91]:
arr1 = np.random.randint(1, 10000, 100)

In [92]:
print(f"Array: {arr1}")
print(f"Mean: {np.mean(arr1)}")
print(f"Average: {np.average(arr1)}")
print(f"Median: {np.median(arr1)}")
print(f"Variance: {np.var(arr1)}")
print(f"Standard Deviation: {np.std(arr1)}")

Array: [6184 6040 7186 7097 7923 3917 9469 3373 5867 6588 9002  923 8710 8426
 9423 5818 1123 2755 3405 8220 7775 3967 4744 8625  900 4229 6236 1112
 6142 5806 9873 1969 4379 4351 9647 3185 2772 5440 8529 6378 7118 4181
 7729 1351 9238 1529 7537 2328 5746 7614 8806 6603 8044 8044 8430 8414
 7955 2569 6783 2940 9507 8738 7435 4329   38 3626 2642 5954 8640 5629
 6961 4509 9488 8213 5911 3775 9614 6648 4382 2657   84  285 5146 3177
 7397 6823  548 1320  183 4344 8677 2925 9913 2764 2380 5884 2325 7367
 6246 4050]
Mean: 5510.01
Average: 5510.01
Median: 5897.5
Variance: 7663734.509899999
Standard Deviation: 2768.3450850462987


In [93]:
# Statistics on multidimentional arrays
arr2 = np.random.randint(1, 100, (6, 8))

In [99]:
print(f"Matrix:\n {arr2}")
print(f"Average y: {np.average(arr2, axis=0)}") # Axis 0 is y and axis 1 is x
print(f"Average x: {np.average(arr2, axis=1)}") # Axis 0 is y and axis 1 is x

Matrix:
 [[ 8 50 18 12 27 31 78 66]
 [49 83 51 87 20 68 88  8]
 [73 31 63 62 21 72 19 24]
 [27 42 30 42 29 47 41 15]
 [73 17 26 34 84 71 33 11]
 [31 38 33 18  1  7 65 67]]
Average y: [43.5        43.5        36.83333333 42.5        30.33333333 49.33333333
 54.         31.83333333]
Average x: [36.25  56.75  45.625 34.125 43.625 32.5  ]
